services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning", "--requirepass", "${DB_PASS}"]
    environment:
      - REDIS_PASSWORD=${DB_PASS} 

volumes:
  redis_data: